### PR TITLE
Add ASN, ISP and other fields

### PR DESCRIPTION
**Pull request by fschlaepfer**

### CODE REVIEW

**Comment by ondrap** [comment]
I have decided that the library needs some slight refactoring after the years and I have exposed more of the internals API. Can you try the HEAD and see if it wouldn't be better for you to parse it directly from the `GeoField`?

**Comment by fschlaepfer** [comment]
That works too. I like the refactoring.

The fields I added are pretty common. If you are going to keep `findGeoData` around alongside `rawGeoData`, you might as well add them for convenience. Otherwise, you might consider exposing `key` and `geoNum` to aid in writing custom parsers.

**Comment by ondrap** [comment]
Ok, can you look at HEAD now if it works correctly for you?

**Comment by fschlaepfer** [comment]
Works great.

Thank you for this library!

**Pull request closed without merging**
